import React from "react";
import { ArrowRight, Clock3, Gauge, GitBranch, Landmark, Share2, ShieldCheck, Sparkles } from "lucide-react";
import { prefetchRoute } from "@/lib/routePrefetch";

const releases = [
  { slug: "performance-public-experience", title: "Performance and public experience", icon: Gauge, notes: ["Workspace pages now load on demand with stable shared framework, data, UI, motion, and icon chunks.", "The welcome screen adds manual light/dark preview and a persisted follow-system theme preference.", "A maintained demo dataset policy now guides community fixtures, screenshots, and examples."] },
  { slug: "open-source-release-readiness", title: "Open-source release readiness", icon: GitBranch, notes: ["Documentation is organized by guides, architecture, maintainers, and product context.", "The repository includes an MIT License, contributor guidance, security policy, CI, pull request, and issue templates.", "The connected GitHub repository remains private until the owner changes visibility."] },
  { slug: "simulation-first-operating-shell", title: "Simulation-first operating shell", icon: ShieldCheck, notes: ["Command, Chat, Wallets, Connections, Settings, and Activity remain policy-bound operator workspaces.", "No wallet keys, venue credentials, signing, custody, live orders, or real execution capability were added."] },
];

const publicChangelogUrl = "https://github.com/FrancKINANI/ai-investment-agent-mvp/blob/main/docs/product/changelog.md";

export default function Changelog() {
  return <div className="changelog-page">
    <header className="welcome-nav"><a className="welcome-brand" href="/welcome" aria-label="Ledgerline welcome" onPointerEnter={() => prefetchRoute("/welcome")} onFocus={() => prefetchRoute("/welcome")}><span><Landmark size={17} /></span><strong>ledgerline</strong><small>release notes</small></a><a className="changelog-open-command" href="/" onPointerEnter={() => prefetchRoute("/")} onFocus={() => prefetchRoute("/")}>Open Command <ArrowRight size={15} /></a></header>
    <main className="changelog-main"><section className="changelog-heading"><span className="eyebrow"><Clock3 size={14} /> PUBLIC CHANGELOG</span><h1>What changed,<br /><em>and why it matters.</em></h1><p>Release notes for Ledgerline’s simulation-first operator workspace. Changes are described in terms of user experience, maintainability, and the safety boundaries that remain in force.</p></section><section className="changelog-timeline">{releases.map((release, index) => { const shareUrl = `${publicChangelogUrl}#${release.slug}`; const shareText = encodeURIComponent(`Ledgerline update: ${release.title}`); return <article id={release.slug} key={release.title}><div className="changelog-marker"><release.icon size={17} /><i /></div><div><span>{index === 0 ? "LATEST" : "FOUNDATION"}</span><h2>{release.title}</h2><ul>{release.notes.map((note) => <li key={note}>{note}</li>)}</ul><div className="changelog-share" aria-label={`Share ${release.title}`}><small>Share update</small><a aria-label={`Share ${release.title} on X`} href={`https://twitter.com/intent/tweet?text=${shareText}&url=${encodeURIComponent(shareUrl)}`} target="_blank" rel="noreferrer"><Share2 size={13} /> X</a><a aria-label={`Share ${release.title} on LinkedIn`} href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`} target="_blank" rel="noreferrer"><Share2 size={13} /> LinkedIn</a></div></div></article>; })}</section><aside className="changelog-footnote"><Sparkles size={16} /><span>For planned work, see the <a href="https://github.com/FrancKINANI/ai-investment-agent-mvp/blob/main/docs/product/roadmap.md" target="_blank" rel="noreferrer">product roadmap</a>. Public links become broadly accessible once the repository is published.</span></aside></main>
  </div>;
}
